// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Carniceria.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Carniceria.Models
{
    public partial class CarniceriaContext
    {
        private ICarniceriaContextProcedures _procedures;

        public virtual ICarniceriaContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CarniceriaContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICarniceriaContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<sp_obtener_clientesResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<sp_obtener_productosResult>().HasNoKey().ToView(null);
        }
    }

    public partial class CarniceriaContextProcedures : ICarniceriaContextProcedures
    {
        private readonly CarniceriaContext _context;

        public CarniceriaContextProcedures(CarniceriaContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_obtener_clientesResult>> sp_obtener_clientesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_clientesResult>("EXEC @returnValue = [dbo].[sp_obtener_clientes]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_productosResult>> sp_obtener_productosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_productosResult>("EXEC @returnValue = [dbo].[sp_obtener_productos]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
