// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Carniceria.DataAccess;
using Microsoft.EntityFrameworkCore;

namespace Carniceria.Models;

public partial class CarniceriaContext : DbContext
{
    public CarniceriaContext(DbContextOptions<CarniceriaContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }
    public static CarniceriaContext CreateDbContext()
    {
        var optionsBuilder = new DbContextOptionsBuilder<CarniceriaContext>();
        optionsBuilder.UseSqlServer(Connect.ConnectionString());

        return new CarniceriaContext(optionsBuilder.Options);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}