// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Carniceria.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Carniceria.Models
{
    public partial interface ICarniceriaContextProcedures
    {
        Task<List<sp_obtener_clientesResult>> sp_obtener_clientesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_productosResult>> sp_obtener_productosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
