// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Carniceria.Models
{
    public partial class sp_consultar_stock_productoResult
    {
        public int? id_producto { get; set; }
        public int? stock_disponible { get; set; }
        [StringLength(28)]
        public string mensaje { get; set; }
    }
}
