// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Carniceria.Models
{
    public partial class sp_insertar_producto_con_stockResult
    {
        public int id_producto { get; set; }
        [StringLength(255)]
        public string nombre_producto { get; set; }
        [StringLength(1)]
        public string tipo { get; set; }
        [Column("precio", TypeName = "decimal(10,2)")]
        public decimal? precio { get; set; }
        public int? cantidad { get; set; }
        public DateTime? fecha_actualizacion { get; set; }
    }
}
