// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Carniceria.Models
{
    public partial class sp_obtener_detalle_deudaResult
    {
        public int? cantidad { get; set; }
        [Column("kilos", TypeName = "decimal(10,2)")]
        public decimal? kilos { get; set; }
        [Column("monto_producto", TypeName = "decimal(10,2)")]
        public decimal? monto_producto { get; set; }
        public string nombre_producto { get; set; }
        public DateTime? fecha_pago { get; set; }
        [Column("monto_pagado", TypeName = "decimal(10,2)")]
        public decimal? monto_pagado { get; set; }
        public int? id_parciales { get; set; }
    }
}
