// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Carniceria.Models
{
    public partial class sp_obtener_clientesResult
    {
        public int id_cliente { get; set; }
        [StringLength(100)]
        public string nombre { get; set; }
        [StringLength(100)]
        public string apellido { get; set; }
        [StringLength(20)]
        public string telefono { get; set; }
        [StringLength(255)]
        public string direccion { get; set; }
        [StringLength(50)]
        public string email { get; set; }
        [StringLength(255)]
        public string info_relevante { get; set; }
        public DateTime? fecha_registro { get; set; }
        [StringLength(1)]
        public string cod_estado { get; set; }
    }
}
